Repository yourfootmyfoot/Footlog-BackEnd, pull requests merged in 2024-09, with the labels that each got.

#19 Feat/match
  build.gradle
  src/main/java/com/yfmf/footlog/match/command/domain/controller/MatchController.java
  src/main/java/com/yfmf/footlog/match/command/domain/model/dao/MatchMapper.java
  src/main/java/com/yfmf/footlog/match/controller/MatchController.java
  src/main/java/com/yfmf/footlog/match/dto/LoadMatchResponseDTO.java
  src/main/java/com/yfmf/footlog/match/dto/MatchRegistRequestDTO.java
  src/main/java/com/yfmf/footlog/match/entity/Match.java
  src/main/java/com/yfmf/footlog/match/entity/MatchSchedule.java
  src/main/java/com/yfmf/footlog/match/entity/MatchService.java
  src/main/java/com/yfmf/footlog/match/entity/Pro.java
  src/main/java/com/yfmf/footlog/match/enums/ClubLevel.java
  src/main/java/com/yfmf/footlog/match/enums/MatchGender.java
  src/main/java/com/yfmf/footlog/match/enums/MatchPlayerQuantity.java
  src/main/java/com/yfmf/footlog/match/enums/MatchStatus.java
  src/main/java/com/yfmf/footlog/match/enums/QuarterQuantity.java
  src/main/java/com/yfmf/footlog/match/repository/MatchRepository.java
  src/test/java/com/yfmf/footlog/match/MatchTests.java
Labels: Refactor

#26 Fix : merge 후 match 수정
  src/main/java/com/yfmf/footlog/domain/match/controller/MatchController.java
  src/main/java/com/yfmf/footlog/domain/match/dto/LoadMatchResponseDTO.java
  src/main/java/com/yfmf/footlog/domain/match/dto/MatchRegistRequestDTO.java
  src/main/java/com/yfmf/footlog/domain/match/entity/Match.java
  src/main/java/com/yfmf/footlog/domain/match/entity/MatchSchedule.java
  src/main/java/com/yfmf/footlog/domain/match/entity/MatchService.java
  src/main/java/com/yfmf/footlog/domain/match/entity/Pro.java
  src/main/java/com/yfmf/footlog/domain/match/enums/ClubLevel.java
  src/main/java/com/yfmf/footlog/domain/match/enums/MatchGender.java
  src/main/java/com/yfmf/footlog/domain/match/enums/MatchPlayerQuantity.java
  src/main/java/com/yfmf/footlog/domain/match/enums/MatchStatus.java
  src/main/java/com/yfmf/footlog/domain/match/enums/QuarterQuantity.java
  src/main/java/com/yfmf/footlog/domain/match/repository/MatchRepository.java
  src/test/java/com/yfmf/footlog/domain/match/MatchTests.java
Labels: FIx

#31 Refactory : match, club 테이블 리펙토링
  data.ddl
  src/main/java/com/yfmf/footlog/domain/club/controller/ClubController.java
  src/main/java/com/yfmf/footlog/domain/club/entity/Club.java
  src/main/java/com/yfmf/footlog/domain/guest/dto/CreateGuestDto.java
  src/main/java/com/yfmf/footlog/domain/guest/dto/UpdateGuestDto.java
  src/main/java/com/yfmf/footlog/domain/guest/entity/Guest.java
  src/main/java/com/yfmf/footlog/domain/guest/repository/GuestRepository.java
  src/main/java/com/yfmf/footlog/domain/guest/service/GuestService.java
  src/main/java/com/yfmf/footlog/domain/match/controller/MatchController.java
  src/main/java/com/yfmf/footlog/domain/match/dto/LoadMatchResponseDTO.java
  src/main/java/com/yfmf/footlog/domain/match/dto/MatchRegistRequestDTO.java
  src/main/java/com/yfmf/footlog/domain/match/entity/Match.java
  src/main/java/com/yfmf/footlog/domain/match/entity/MatchSchedule.java
  src/main/java/com/yfmf/footlog/domain/match/enums/ClubLevel.java
  src/main/java/com/yfmf/footlog/domain/match/enums/MatchGender.java
  src/main/java/com/yfmf/footlog/domain/match/enums/MatchPlayerQuantity.java
  src/main/java/com/yfmf/footlog/domain/match/enums/MatchStatus.java
  src/main/java/com/yfmf/footlog/domain/match/enums/QuarterQuantity.java
  src/main/java/com/yfmf/footlog/domain/match/service/MatchService.java
  src/test/java/com/yfmf/footlog/domain/match/MatchTests.java
Labels: Refactor

#32 Refactory : match 테이블 리펙토링
  src/main/java/com/yfmf/footlog/domain/match/entity/Match.java
Labels: Refactor

#36 Feat/club
  src/main/java/com/yfmf/footlog/config/SecurityConfig.java
  src/main/java/com/yfmf/footlog/config/WebConfig.java
  src/main/java/com/yfmf/footlog/domain/auth/dto/LoginedInfo.java
  src/main/java/com/yfmf/footlog/domain/auth/jwt/JWTTokenProvider.java
  src/main/java/com/yfmf/footlog/domain/club/controller/ClubController.java
  src/main/java/com/yfmf/footlog/domain/club/controller/ClubMemberController.java
  src/main/java/com/yfmf/footlog/domain/club/dto/ClubMemberResponseDTO.java
  src/main/java/com/yfmf/footlog/domain/club/dto/ClubRegistRequestDTO.java
  src/main/java/com/yfmf/footlog/domain/club/entity/ClubMember.java
  src/main/java/com/yfmf/footlog/domain/club/entity/ClubMemberRole.java
  src/main/java/com/yfmf/footlog/domain/club/repository/ClubMemberRepository.java
  src/main/java/com/yfmf/footlog/domain/club/service/ClubMemberService.java
  src/main/java/com/yfmf/footlog/domain/club/service/ClubService.java
  src/main/java/com/yfmf/footlog/domain/member/controller/MemberSocialLoginController.java
  src/main/java/com/yfmf/footlog/domain/member/service/MemberService.java
  src/main/java/com/yfmf/footlog/error/ErrorCode.java
  src/main/java/com/yfmf/footlog/exception/GlobalExceptionHandler.java
  src/test/java/com/yfmf/footlog/domain/club/ClubMemberTests.java
Labels: Feat

#42 Refactory : Club, Member, user, match, matchenroll
  data.ddl
  src/main/java/com/yfmf/footlog/domain/guest/dto/CreateGuestDto.java
  src/main/java/com/yfmf/footlog/domain/match/controller/MatchController.java
  src/main/java/com/yfmf/footlog/domain/match/dto/LoadMatchResponseDTO.java
  src/main/java/com/yfmf/footlog/domain/match/dto/MatchRegistRequestDTO.java
  src/main/java/com/yfmf/footlog/domain/match/service/MatchService.java
  src/main/java/com/yfmf/footlog/domain/member/domain/Member.java
  src/main/java/com/yfmf/footlog/domain/member/domain/Record.java
  src/main/java/com/yfmf/footlog/domain/member/domain/Stat.java
  src/main/java/com/yfmf/footlog/domain/member/domain/UserRole.java
  src/main/java/com/yfmf/footlog/domain/member/dto/MemberSaveRequestDto.java
  src/main/java/com/yfmf/footlog/domain/member/dto/MemberUpdateRequestDto.java
  src/main/java/com/yfmf/footlog/domain/member/enums/Area.java
  src/main/java/com/yfmf/footlog/domain/member/enums/MainFoot.java
  src/main/java/com/yfmf/footlog/domain/member/enums/Position.java
  src/main/java/com/yfmf/footlog/domain/member/service/MemberService.java
  src/main/java/com/yfmf/footlog/users/entity/User.java
  src/main/java/com/yfmf/footlog/users/repository/UserRepository.java
  src/main/java/com/yfmf/footlog/users/service/UserService.java
Labels: Refactor

#44 Chore: .gitmessage.txt 추가
  .gitmessage.txt
Labels: Chore

#46 feat/domain 브랜치 생성
  src/main/java/com/yfmf/footlog/domain/domain/Repository/asdf
  src/main/java/com/yfmf/footlog/domain/domain/controller/asdf
  src/main/java/com/yfmf/footlog/domain/domain/dto/md
  src/main/java/com/yfmf/footlog/domain/domain/entity/asdf
  src/main/java/com/yfmf/footlog/domain/domain/enums/asdf
  src/main/java/com/yfmf/footlog/domain/domain/exception/asdf
  src/main/java/com/yfmf/footlog/domain/domain/service/asdf
Labels: Feat

#49 Feat/club
  src/main/java/com/yfmf/footlog/config/DataLoader.java
  src/main/java/com/yfmf/footlog/domain/club/controller/ClubController.java
  src/main/java/com/yfmf/footlog/domain/club/controller/ClubMemberController.java
  src/main/java/com/yfmf/footlog/domain/club/service/ClubMemberService.java
  src/main/java/com/yfmf/footlog/domain/club/service/ClubService.java
  src/main/java/com/yfmf/footlog/domain/member/controller/MemberController.java
  src/main/java/com/yfmf/footlog/domain/member/controller/MemberSocialLoginController.java
  src/main/java/com/yfmf/footlog/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/yfmf/footlog/domain/member/service/MemberService.java
  src/main/java/com/yfmf/footlog/exception/GlobalExceptionHandler.java
Labels: Refactor
