Repository yourfootmyfoot/Footlog-BackEnd, pull requests merged in 2024-10, with the labels that each got.

#57 Feat: 경기 등록 도메인
  src/main/java/com/yfmf/footlog/domain/match/controller/MatchController.java
  src/main/java/com/yfmf/footlog/domain/match/dto/LoadMatchResponseDTO.java
  src/main/java/com/yfmf/footlog/domain/match/dto/MatchRegisterRequestDTO.java
  src/main/java/com/yfmf/footlog/domain/match/dto/MatchResponseDTO.java
  src/main/java/com/yfmf/footlog/domain/match/entity/Match.java
  src/main/java/com/yfmf/footlog/domain/match/entity/MatchSchedule.java
  src/main/java/com/yfmf/footlog/domain/match/service/MatchService.java
Labels: Feat

#61 Test/club TestCode 작성
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/⚒️리팩토링.md
  README.md
  src/main/java/com/yfmf/footlog/domain/club/entity/Club.java
  src/main/java/com/yfmf/footlog/domain/club/service/ClubService.java
  src/main/java/com/yfmf/footlog/domain/domain/Repository/asdf
  src/main/java/com/yfmf/footlog/domain/domain/controller/asdf
  src/main/java/com/yfmf/footlog/domain/domain/dto/md
  src/main/java/com/yfmf/footlog/domain/domain/entity/asdf
  src/main/java/com/yfmf/footlog/domain/domain/enums/asdf
  src/main/java/com/yfmf/footlog/domain/domain/exception/asdf
  src/main/java/com/yfmf/footlog/domain/domain/service/asdf
  src/main/java/com/yfmf/footlog/domain/guest/controller/GuestController.java
  src/main/java/com/yfmf/footlog/domain/guest/dto/CreateGuestDto.java
  src/main/java/com/yfmf/footlog/domain/guest/dto/GuestSaveRequestDto.java
  src/main/java/com/yfmf/footlog/domain/guest/dto/GuestUpdateRequestDto.java
  src/main/java/com/yfmf/footlog/domain/guest/entity/Guest.java
  src/main/java/com/yfmf/footlog/domain/guest/repository/GuestRepository.java
  src/main/java/com/yfmf/footlog/domain/guest/service/GuestService.java
  src/main/java/com/yfmf/footlog/domain/match/controller/MatchController.java
  src/main/java/com/yfmf/footlog/domain/match/dto/LoadMatchResponseDTO.java
  src/main/java/com/yfmf/footlog/domain/match/dto/MatchRegisterRequestDTO.java
  src/main/java/com/yfmf/footlog/domain/match/dto/MatchResponseDTO.java
  src/main/java/com/yfmf/footlog/domain/match/entity/Match.java
  src/main/java/com/yfmf/footlog/domain/match/entity/MatchSchedule.java
  src/main/java/com/yfmf/footlog/domain/match/service/MatchService.java
  src/main/java/com/yfmf/footlog/error/ErrorCode.java
  src/test/java/com/yfmf/footlog/domain/club/ClubControllerTest.java
  src/test/java/com/yfmf/footlog/domain/club/ClubTests.java
  src/test/java/com/yfmf/footlog/domain/guest/entity/GuestIntegrationTest.java
  src/test/java/com/yfmf/footlog/domain/guest/entity/GuestServiceUnitTests.java
  src/test/java/com/yfmf/footlog/guest/entity/GuestSchemeTest.java
  src/test/java/com/yfmf/footlog/guest/entity/GuestServiceIntegrationTests.java
  src/test/java/com/yfmf/footlog/guest/entity/GuestServiceUnitTests.java
Labels: Test

#48 Feat: feat/admin 브랜치 이름 변경, Spring AOP를 이용한 logging 구현, 기능 추가 필요
  src/main/java/com/yfmf/footlog/FootlogApplication.java
  src/main/java/com/yfmf/footlog/config/SecurityConfig.java
  src/main/java/com/yfmf/footlog/domain/admin/dto/md
  src/main/java/com/yfmf/footlog/domain/admin/entity/asdf
  src/main/java/com/yfmf/footlog/domain/admin/enums/asdf
  src/main/java/com/yfmf/footlog/domain/admin/exception/asdf
  src/main/java/com/yfmf/footlog/domain/admin/repository/AdminRepository.java
  src/main/java/com/yfmf/footlog/domain/admin/repository/asdf
  src/main/java/com/yfmf/footlog/domain/admin/service/AdminService.java
  src/main/java/com/yfmf/footlog/domain/admin/service/asdf
  src/main/java/com/yfmf/footlog/domain/domain/exception/asdf
  src/main/java/com/yfmf/footlog/domain/domain/service/asdf
  src/main/java/com/yfmf/footlog/logging/LoggingAspect.java
  src/test/java/com/yfmf/footlog/domain/admin/controller/LoggingAspectTest.java
Labels: Feat

#65 Feat/club
  .github/scripts/chatgpt_code_review.py
  .github/workflows/chatgpt-code-review.yml
  .gitignore
  src/main/java/com/yfmf/footlog/domain/auth/exception/LoginRequiredException.java
  src/main/java/com/yfmf/footlog/domain/auth/jwt/JWTTokenProvider.java
  src/main/java/com/yfmf/footlog/domain/auth/refreshToken/exception/RedisSaveFailed.java
  src/main/java/com/yfmf/footlog/domain/auth/refreshToken/repository/RefreshTokenRepository.java
  src/main/java/com/yfmf/footlog/domain/auth/refreshToken/service/RefreshTokenService.java
  src/main/java/com/yfmf/footlog/domain/auth/utils/SecurityUtils.java
  src/main/java/com/yfmf/footlog/domain/club/controller/ClubController.java
  src/main/java/com/yfmf/footlog/domain/club/controller/ClubMemberController.java
  src/main/java/com/yfmf/footlog/domain/club/dto/ClubRegistRequestDTO.java
  src/main/java/com/yfmf/footlog/domain/club/exception/ClubDuplicatedException.java
  src/main/java/com/yfmf/footlog/domain/club/exception/ClubNotFoundException.java
  src/main/java/com/yfmf/footlog/domain/club/exception/IllegalClubArgumentException.java
  src/main/java/com/yfmf/footlog/domain/guest/service/GuestService.java
  src/main/java/com/yfmf/footlog/domain/match/controller/MatchController.java
  src/main/java/com/yfmf/footlog/domain/member/controller/MemberController.java
  src/main/java/com/yfmf/footlog/domain/member/controller/MemberSocialLoginController.java
  src/main/java/com/yfmf/footlog/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/yfmf/footlog/domain/member/service/MemberService.java
  src/main/java/com/yfmf/footlog/domain/member/service/MemberSocialLoginService.java
  src/main/java/com/yfmf/footlog/error/ApplicationException.java
  src/main/java/com/yfmf/footlog/error/ErrorCode.java
  src/main/java/com/yfmf/footlog/error/ErrorResponse.java
  src/main/java/com/yfmf/footlog/error/GlobalControllerAdvice.java
  src/main/java/com/yfmf/footlog/exception/ErrorCode.java
  src/main/java/com/yfmf/footlog/exception/GlobalExceptionHandler.java
  src/main/java/com/yfmf/footlog/exception/RootException.java
  src/main/java/com/yfmf/footlog/logging/LoggingAspect.java
Labels: Feat

#68 Feat: System 로그
  .gitignore
  build.gradle
  data.ddl
  src/main/java/com/yfmf/footlog/config/AOPConfig.java
  src/main/java/com/yfmf/footlog/domain/admin/controller/AdminController.java
  src/main/java/com/yfmf/footlog/logging/AllLogAdviser.java
  src/main/java/com/yfmf/footlog/logging/ClubLogAdviser.java
  src/main/java/com/yfmf/footlog/logging/GuestLogAdviser.java
  src/main/java/com/yfmf/footlog/logging/MatchLogAdviser.java
  src/main/java/com/yfmf/footlog/logging/MemberLogAdviser.java
  src/main/java/com/yfmf/footlog/logging/Pointcuts.java
  src/main/resources/file-error-appender.xml
  src/main/resources/file-warn-appender.xml
  src/main/resources/log-info-appender.xml
  src/main/resources/logback-spring.xml
Labels: Feat

#79 Feat/club
  src/main/java/com/yfmf/footlog/domain/club/controller/ClubController.java
  src/main/java/com/yfmf/footlog/domain/club/controller/ClubMemberController.java
  src/main/java/com/yfmf/footlog/domain/club/entity/ClubMember.java
  src/main/java/com/yfmf/footlog/domain/club/enums/ClubMemberRole.java
  src/main/java/com/yfmf/footlog/domain/club/exception/ClubAlreadyJoinedException.java
  src/main/java/com/yfmf/footlog/domain/club/repository/ClubMemberRepository.java
  src/main/java/com/yfmf/footlog/domain/club/service/ClubMemberService.java
  src/main/java/com/yfmf/footlog/domain/club/service/ClubService.java
  src/main/java/com/yfmf/footlog/error/GlobalControllerAdvice.java
Labels: Feat

#109 Feat/club
  .gitignore
  src/main/java/com/yfmf/footlog/FootlogApplication.java
  src/main/java/com/yfmf/footlog/domain/member/controller/MemberController.java
  src/main/java/com/yfmf/footlog/domain/member/controller/MemberSocialLoginController.java
  src/main/java/com/yfmf/footlog/domain/member/domain/Authority.java
  src/main/java/com/yfmf/footlog/domain/member/service/MemberService.java
Labels: FIx

#112 Feat/club
  .gitignore
  src/main/java/com/yfmf/footlog/config/SecurityConfig.java
  src/main/java/com/yfmf/footlog/domain/member/controller/MemberController.java
  src/main/java/com/yfmf/footlog/domain/member/domain/Authority.java
  src/main/java/com/yfmf/footlog/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/yfmf/footlog/domain/member/service/MemberService.java
Labels: Feat

#113 Feat/club
  .gitignore
  src/main/java/com/yfmf/footlog/domain/auth/jwt/JWTTokenProvider.java
  src/main/java/com/yfmf/footlog/domain/auth/refreshToken/service/RefreshTokenService.java
  src/main/java/com/yfmf/footlog/domain/club/controller/ClubController.java
  src/main/java/com/yfmf/footlog/domain/club/controller/ClubMemberController.java
  src/main/java/com/yfmf/footlog/domain/club/dto/ClubDetailResponseDTO.java
  src/main/java/com/yfmf/footlog/domain/club/service/ClubMemberService.java
  src/main/java/com/yfmf/footlog/domain/member/service/MemberService.java
Labels: Feat

#115 Feat: 매칭을 신청할 수 있다 #114
  src/main/java/com/yfmf/footlog/domain/match/controller/MatchController.java
  src/main/java/com/yfmf/footlog/domain/match/entity/Match.java
  src/main/java/com/yfmf/footlog/domain/match/enums/MatchStatus.java
  src/main/java/com/yfmf/footlog/domain/match/service/MatchService.java
Labels: Feat

#123 Fix: admin 멤버 전체조회 수정
  src/main/java/com/yfmf/footlog/config/DataLoader.java
  src/main/java/com/yfmf/footlog/domain/auth/jwt/JWTTokenProvider.java
  src/main/java/com/yfmf/footlog/domain/member/domain/Authority.java
  src/main/java/com/yfmf/footlog/domain/member/domain/Member.java
  src/main/java/com/yfmf/footlog/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/yfmf/footlog/domain/member/service/MemberService.java
  src/main/java/com/yfmf/footlog/domain/member/service/MemberSocialLoginService.java
Labels: FIx

#124 Feat: 회원 삭제 기능 추가(admin 계정만가능)
  src/main/java/com/yfmf/footlog/domain/member/controller/MemberController.java
  src/main/java/com/yfmf/footlog/domain/member/dto/MemberDeleteResponseDTO.java
  src/main/java/com/yfmf/footlog/domain/member/service/MemberService.java
  src/main/java/com/yfmf/footlog/error/ErrorCode.java
Labels: Feat

#128 Hotfix: @RequestParam parameter 명시
  src/main/java/com/yfmf/footlog/domain/match/controller/MatchController.java
Labels: FIx

#136 Refactor: 필요없는 로그 삭제, dll 수정
  data.ddl
  src/main/java/com/yfmf/footlog/config/SecurityConfig.java
  src/main/java/com/yfmf/footlog/logging/AllLogAdviser.java
  src/main/java/com/yfmf/footlog/logging/LoggingAspect.java
Labels: Refactor
